# Generated by Django 2.2.2 on 2019-06-26 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assistant',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='assistant_courses', to='coaches.Coach'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='course',
            name='coach',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='coach_courses', to='coaches.Coach'),
            preserve_default='True',
        ),
    ]
